language: r
cache: packages

r_check_args: '--as-cran'
warnings_are_errors: true

addons:
  apt:
    packages:
     - libgsl0-dev
     - gsl-bin
  homebrew:
    packages: gsl

#env:
#  global:
#    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE

# build matrix
matrix:
  include:
  - r: devel
    os: linux
    dist: trusty
#    apt_packages:
#     - libgsl-dev
#     - gsl-bin
# Pb with devel version not found with curl; see
#https://travis-ci.community/t/r-development-version-3-7-does-not-work-for-mac/4074
#  - r: devel
#    os: osx
#    osx_image: xcode10.2
#    brew_packages: gsl
  - r: release
    os: linux
    dist: trusty
#    apt_packages:
#     - libgsl-dev
#     - gsl-bin
  - r: release
    os: osx
    osx_image: xcode10.2
#    brew_packages: gsl


#before_install:
#  - sudo apt-get update
#  - Rscript -e 'update.packages(ask = FALSE)'

############################
# better caching for Travis
# See : https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
###########################
#cache:
#  - ccache

